env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:effector/recommended
  - plugin:react-hooks/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - effector
rules:
  react/react-in-jsx-scope:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  effector/enforce-store-naming-convention: 
    - 'error'
  effector/enforce-effect-naming-convention: 
    - 'error'
  effector/enforce-gate-naming-convention: 
    - 'error'
