// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectBySSH(arg1) {
  return window['go']['connections']['Connections']['ConnectBySSH'](arg1);
}

export function ConnectByVNC(arg1) {
  return window['go']['connections']['Connections']['ConnectByVNC'](arg1);
}
