// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {computers} from '../models';
import {context} from '../models';

export function CheckAllSSH():Promise<void>;

export function CheckAllVNC():Promise<void>;

export function CheckSSH(arg1:string):Promise<computers.NodeStatus>;

export function CheckVNC(arg1:string):Promise<computers.NodeStatus>;

export function GetComputersList():Promise<Array<computers.ComputerItem>>;

export function LoadComputers():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
