// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {traceroute} from '../models';
import {context} from '../models';

export function CheckPath(arg1:string):Promise<void>;

export function FixResult():Promise<traceroute.Result>;

export function FixTracertNode():Promise<traceroute.TracertedNode>;

export function SetContext(arg1:context.Context):Promise<void>;
