// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAllSSH() {
  return window['go']['main']['Computer']['CheckAllSSH']();
}

export function CheckAllVNC() {
  return window['go']['main']['Computer']['CheckAllVNC']();
}

export function CheckSSH(arg1) {
  return window['go']['main']['Computer']['CheckSSH'](arg1);
}

export function CheckVNC(arg1) {
  return window['go']['main']['Computer']['CheckVNC'](arg1);
}

export function GetComputersList() {
  return window['go']['main']['Computer']['GetComputersList']();
}

export function LoadComputers() {
  return window['go']['main']['Computer']['LoadComputers']();
}
