// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAllSSH():Promise<void>;

export function CheckAllVNC():Promise<void>;

export function CheckSSH(arg1:string):Promise<main.NodeStatus>;

export function CheckVNC(arg1:string):Promise<main.NodeStatus>;

export function GetComputersList():Promise<Array<main.ComputerItem>>;

export function LoadComputers():Promise<void>;
