// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSSH(arg1:string):Promise<boolean>;

export function CheckVNC(arg1:string):Promise<boolean>;
