// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSSH(arg1) {
  return window['go']['main']['Ports']['CheckSSH'](arg1);
}

export function CheckVNC(arg1) {
  return window['go']['main']['Ports']['CheckVNC'](arg1);
}
