// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPath(arg1) {
  return window['go']['main']['Traceroute']['CheckPath'](arg1);
}

export function FixResult() {
  return window['go']['main']['Traceroute']['FixResult']();
}

export function FixTracertNode() {
  return window['go']['main']['Traceroute']['FixTracertNode']();
}
