// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPath(arg1:string):Promise<void>;

export function FixResult():Promise<main.Result>;

export function FixTracertNode():Promise<main.TracertedNode>;
